### ISSUE TITLE
Set-up automatic deployment of dev version on successful master commit

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#162]
We want a new dev release for each master commit, so this should be done automatically by CI

**Comment by chrgernoe** [comment]
In general, this is not possible because we can only make one dev release each day. This is limited by the current version schema of the dev release. Another limitation is e.g. that F-Droid needs some days until the dev release is available. Google is faster in this case. Here one dev release per day would be possible.

If we really need more than one release, Google offers the way of so called internal track which is much faster available. But be honest, I don't see the need at the moment. In this case we need a slight change of the version schema but that should be possible an compatible with the current on.

I agree on the need of continuous delivery for the development version but only one version a day and only, if something changed in the repository. In this case, I would request the deletion of the dev release from the F-Droid store because due to the build delay it makes no sense. In addition I would make the dev release in the Google play store only available for invited testers/developer (closed bata test).

**Comment by paetz** [comment]
Ok. So the automatic process would be like:
Once per day, check if master state has changed. If yes, deploy new dev release.

**Comment by chrgernoe** [comment]
Exactly

**Comment by chrgernoe** [comment]
@paetz : Do we want to close this issue because the offline discussion brought up the following arguments against this feature?
* As stated in the maintainer docu, building a release is very easy. Hence, this feature may be over engineering at the moment.
* To check, if there is commit in the repo is not enough because e.g. if a small docu change is done, no new app shall be built. Hence, the check will be more complicated.

**Comment by paetz** [comment]
I agree. Closed.
