### ISSUE TITLE
Update country and region lists on updating all

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#285]
In #281 we moved the update mechanism to a specialized region manager but forgot to add an opportunity to update country and region lists.

Todo: Update country list and all region lists of already downloaded countries in
A) the already existing menu point "Alle aktualisieren" or
B) in a separate menu point (because updating all sectors might be pretty time consuming in case you only want to get a newly added country.

**Comment by paetz** [comment]
A) and B) have some disadvantages regarding implementation. Hence, I suggest
C) Adding a start-up activity with white screen and yac logo that updates country and region lists automatically on starting the app. Since the amount of data is quite low for these updates, it should be fine to do this also if WiFi is not available. The start-up activity is also the base for #248

**Comment by chrgernoe** [comment]
I would add a separate menu point. But you are talking about the menu in the region manager, right?

**Comment by paetz** [comment]
What do you think about option C in my comment?

**Comment by chrgernoe** [comment]
Sorry, I somehow overlooked your last comment. 

Generally it is good idea but I see a problem if the mobile network connection is very pure, what is not seldom in Germany. In this case the app would take forever even if the data amount is low. Hence, the update process must be a background process. It is possible but it is probably a bit complicated to handle becuse the app must handle a user update, it the automatic update is already in progress.

Even this problem can be solved, I still would implement option B because otherwise the user must always restart the app for an update. It's bit like Windows where an restart is required for everything.

**Comment by paetz** [comment]
Got your point. However, I would prefer A over B because the case that a new country or region is added is extremely rare and it is always a good idea to do db updates from time to time (see the last problem with the rocks without type).

**Comment by chrgernoe** [comment]
> Got your point. However, I would prefer A over B because the case that a new country or region is added is extremely rare and it is always a good idea to do db updates from time to time (see the last problem with the rocks without type).

OK. That's fine for me.
